### ISSUE TITLE
Cache database lookup for words

### ISSUE THREAD

**Issue by chriskamphuis** [informagi/REL#100]
### Problem 

The database call at: 

https://github.com/informagi/REL/blob/main/REL/db/base.py#L143

is called multiple times with the same word as input, caching this speeds up the function here 3x for long documents:

https://github.com/informagi/REL/blob/37671e6be9207b410c09d578b671f7014c5f96b1/REL/entity_disambiguation.py#L455

### Solution:

Replace the function with this:

```
@lru_cache()
def lookup_word(self, word, c, table_name, column="emd"):
    return c.execute(
            "select {} from {} where word = :word".format(column, table_name),
            {"word": word},
        ).fetchone()

def lookup(self, w, table_name, column="emb"):
    """
    Args:
        w: word to look up.
    Returns:
        embeddings for ``w``, if it exists.
        ``None``, otherwise.
    """
    c = self.db.cursor()

    res = []
    c.execute("BEGIN TRANSACTION;")
    for word in w:
        e = self.lookup_word(word, c, table_name, column)
        res.append(e if e is None else array("f", e[0]).tolist())
    c.execute("COMMIT;")

    return res
```

**Comment by arjenpdevries** [comment]
Shouldn't the query be a join in SQL instead of a nested loop join in client code?
