### ISSUE TITLE
EL returns AttributeError as 'function' object has no attribute 'format_spans'

### ISSUE THREAD

**Issue by Jingstd** [informagi/REL#103]
Hi,
   I set a server locally, and run the example EL and ED to connect to the server, the EL inputs an empty span, ED inputs a non-empty span. 
However, the ED returns ok, the EL returns an exception: 
**************Encountered exception1: AttributeError("'function' object has no attribute 'format_spans'",)*********

the console output of the server is :
**********************simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)******************

Did I set something wrong with the server ?

**Comment by Jingstd** [comment]
update: the exception is :
***********************Encountered exception1: AttributeError("'Span' object has no attribute 'start_pos'",)************

**Comment by Jingstd** [comment]
update:
I found out that the 'span' object has attribute 'start_position' instead of 'start_pos'
in file mention_detection.py line149.

**Comment by KDercksen** [comment]
Hi, thanks for your updates! It seems that this is a Flair breaking change that was introduced recently.
