### ISSUE TITLE
Flair: Span attribute breaking change

### ISSUE THREAD

**Issue by KDercksen** [informagi/REL#104]
Flair spans now expose the start/end position as `start_position` and `end_position` instead of `start_pos` / `end_pos`, this should be reflected in `mention_detection.py`

**Comment by tomaszpietruszka-globality** [comment]
For other people that bump into this and need a quick work-around: Flair 0.11 introduced the change, so `flair<0.11` should work.

After downgrading `flair` I also had to manually install `sacremoses` - but perhaps that wouldn't happen if I started fresh
