### ISSUE TITLE
Using REL with another knowledge base

### ISSUE THREAD

**Issue by JoaoFerreira7** [informagi/REL#105]
Hi! I'm currently trying to think on a way to use REL for a specific case. Let's say I want to use a database given by a someone/company and i want to perform entity linking on the items of that database. Is there a way to perform this, instead of using Wikipedia as a KB? If so, what changes would I need to do?

Thanks in advance, I'm new to this so I don't have that many knowledge yet.

**Comment by hasibi** [comment]
Hi,

Using REL with another knowledge graph is doable, but requires quite some effort. 
1. You need to obtain entity embeddings by using a  knowledge graph embedding algorithm (we use Wikipedia2Vec for REL).
2. You need to create an index for prior probability of entities using a text corpus (i.e., P(e|m) probabilities).
3. You need to have training data  to re-train the mention selection and entity disambiguation models.

If you are working with a domain-specific KB, I suggest you to use one of the few-shot EL approaches.
