### ISSUE TITLE
API Status

### ISSUE THREAD

**Issue by kmdn** [informagi/REL#115]
Hey there!

Love the linker!

Unfortunately it seems to be down (my API calls are timing out and the API Status badge on git has trouble fetching the data) - do you more or less know when it will be up?

Thanks again for the great work & wishing a great week!

Best regards,
kmdn

**Comment by chriskamphuis** [comment]
Not sure what happened, but the API seems to be running correctly right now. 
If you still have this issue, feel free to re-open this issue.
