### ISSUE TITLE
Memory Leak in REL API

### ISSUE THREAD

**Issue by abhinavkulkarni** [informagi/REL#126]
Hi,

I am currently experimenting with the REL API for a personal project and have found out that the docker image leaks memory.

Here's a screenshot of `docker stats` when all docker containers were instantiated. The REL API docker container name is `rel_nlp-app_1`. The container is restricted to using 3GB of memory.

![image](https://user-images.githubusercontent.com/1565547/200171107-d3806fe0-7d97-4bc9-8aeb-9f6c3296c581.png)

After 30 mins or so of hitting API, the memory usage crosses the memory limit forcing the container to restart (I am suing `restart: always` in `docker-compose.yml`).
![image](https://user-images.githubusercontent.com/1565547/200171332-2ea3ab32-539b-4f00-835c-1d2d2d76146e.png)

Are there any pointers as to where to look for this memory leak?

Thanks!

**Comment by KDercksen** [comment]
Hi,

We use `lru_cache` without a maximum cache size, that might be (one of?) the cause.

https://github.com/informagi/REL/blob/main/REL/mention_detection_base.py#L43
https://github.com/informagi/REL/blob/main/REL/mention_detection_base.py#L58
https://github.com/informagi/REL/blob/dd99c542913c753d58ffc251e9b9e94f273dd60c/REL/db/base.py#L145
https://github.com/informagi/REL/blob/dd99c542913c753d58ffc251e9b9e94f273dd60c/REL/db/base.py#L153
https://github.com/informagi/REL/blob/dd99c542913c753d58ffc251e9b9e94f273dd60c/REL/utils.py#L128
https://github.com/informagi/REL/blob/dd99c542913c753d58ffc251e9b9e94f273dd60c/REL/utils.py#L183

You could maybe try restricting the max cache size and see if that solves the problem?

**Comment by stefsmeets** [comment]
Could you pull the latest version and see if #127 helped with your problem? This should significantly reduce the number of cached items from database lookups.
