### ISSUE TITLE
Publishing to pypi

### ISSUE THREAD

**Issue by stefsmeets** [informagi/REL#132]
Hi all,

I'm preparing the repo to publish the code on [pypi](https://pypi.org). Here is what needs to be done:

### First release

- [x] Decide on a package name on pypi
- [x] Make a manual upload to pypi. You can do this with `build` and `twine`:

```console
pip install twine build
python -m build
twine upload dist/*
```

I recommend using [testpypi](https://packaging.python.org/en/latest/guides/using-testpypi/) if this is the first time.

- [x] #143
- [x] Go to your pypi settings and register an API token scoped to REL: https://pypi.org/manage/account/token/
- [x] Add the token to this repo's secrets named `PYPI_TOKEN`: https://github.com/informagi/REL/settings/secrets/actions

I'm happy to do this, but I think it would be better if @chriskamphuis @KDercksen or @mickvanhulst takes care of this part.

Afterwards, this github action will take care of the rest:
https://github.com/informagi/REL/blob/bump2version/.github/workflows/publish.yml

- [x] Give maintainer/owner access to @chriskamphuis / @KDercksen / ... ?

### New releases

The workflow then becomes as follows:

1. Bump the version (`major`/`minor`/`patch` as needed)
```console
bumpversion minor
```
2. Make a new [release](https://github.com/informagi/REL/releases). The [upload to pypi](https://github.com/informagi/REL/actions/workflows/publish.yml) is triggered when a release is published. Make sure the tag matches the version.

If you use the issue/PR workflow, it's really easy to make changelogs this way too.

**Comment by stefsmeets** [comment]
Alright, it seems like we all settled on `radboud-el`, I will make a first release available on pypi.

**Comment by stefsmeets** [comment]
https://pypi.org/project/radboud-el/

**Comment by stefsmeets** [comment]
@KDercksen @chriskamphuis
If you have an account on [pypi](https://pypi.org), can you give me your usernames? Then I will add you as maintainers for the package.

**Comment by chriskamphuis** [comment]
My account is chriskamphuis

**Comment by KDercksen** [comment]
Mine is https://pypi.org/user/KDercksen/

**Comment by stefsmeets** [comment]
Cool, I added you both as owner. The only thing now is to test the automated release in due time. But this issue can be closed :-)
