### ISSUE TITLE
Error when using prebuilt docker image

### ISSUE THREAD

**Issue by flackbash** [informagi/REL#136]
Hi,

I set up the server on my machine by running the following commands from the README

```
./scripts/download_data.sh ./data generic wiki_2019
docker pull informagi/rel
docker run \
    -p 5555:5555 \
    -v $PWD/data/:/workspace/data \
    --rm -it informagi/rel \
    python -m REL.server --bind 0.0.0.0 --port 5555 /workspace/data wiki_2019
```

However, when I try to query the system using the example EL code from the README with my own API URL, I get the following server output:

```
[28/Nov/2022 09:33:23] "POST /api HTTP/1.1" 200 -
Encountered exception: ValueError('invalid literal for int() with base 2: b\'[["Charles_Bukowski",\'')
[28/Nov/2022 09:33:23] "POST /api HTTP/1.1" 400 -
```

Here is my client code for reproducibility:
```
import requests

API_URL = "http://myhostname:5555/"
text_doc = "If you're going to try, go all the way - Charles Bukowski"

# Example EL.
el_result = requests.post(API_URL, json={
    "text": text_doc,
    "spans": []
}).json()
print(el_result)
```
If I build the docker image myself instead of pulling it from informagi/rel, the error does not occur.

**Comment by arjenpdevries** [comment]
@kdercksen / @mickvanhulst  is the docker image at docker hub up to date?

**Comment by stefsmeets** [comment]
We could use the [Github container registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry). I'd be happy to have a look at this.

**Comment by KDercksen** [comment]
Great :D in the meantime, the Dockerhub image is now updated.

**Comment by flackbash** [comment]
Great, thank you for looking into this :)

**Comment by stefsmeets** [comment]
Automated builds and upload to dockerhub seems to work now:
- https://github.com/informagi/REL/actions/runs/3621550803
- https://hub.docker.com/r/informagi/rel

I made it so that the action syncs with github releases. This helps with versioning and preserves some compute resources. You can also trigger the action manually [here](https://github.com/informagi/REL/actions/workflows/docker_publish.yaml).
