### ISSUE TITLE
Updating the entity DB periodically

### ISSUE THREAD

**Issue by abhinavkulkarni** [informagi/REL#137]
Hi,

Thanks for the great project! I am pretty impressed by the internal engineering of this project and how quickly the API returns the results for a given text.

However, the API works on a specific dump of Wikipedia data. Hence it would not be possible to update the DB  (`Wikipedis2vec` entity and word embeddings) periodically with newer entities as the embeddings are learned in some CBOW fashion on a given dump. This makes it difficult to analyze the latest additions to Wikipedia (such as [`Stable Diffusion`](https://en.wikipedia.org/wiki/Stable_Diffusion) added after 2019).

Like, most state-of-the-art EL systems, REL is two-staged - candidate selection followed by candidate ranking/scoring. 

How difficult would it be to replace the candidate selection step of REL with something else? 

E.g., I have been experimenting with Facebook AI Research's [`BLINK`](https://github.com/facebookresearch/BLINK) framework, which is also two-staged as REL. The candidate selection stage uses two separate encoders (BERT models) to model the similarity between a mention and an entity. This has the advantage of pre-computing entity embeddings and using approx. Nearest neighbor search index to retrieve `top_k` candidates for the 2nd stage relatively quickly. It also allows one to create embeddings for previously unseen entities by embedding their titles and texts and regularly updating the approx-nearest neighbor index, which is not that expensive (say, daily).

However, BLINK does not jointly model the mention-candidate entity pairs globally. That is where REL outshines.

It would be nice to have an EL system that uses BLINK's candidate selection mechanism and REL's candidate ranking/scoring mechanism. This may produce slightly worse results as the 2nd stage of REL also relies on `Wikipedia2vec` embeddings - instead, it'll have to use BLINK's 1st stage entity embeddings - but perhaps the tradeoff would be worth it to a lot of people who want to update entity embeddings regularly.

I am not sure if this proposal makes sense, but I would like to hear some thoughts on this.

Thanks!

**Comment by arjenpdevries** [comment]
Thanks for bringing this up - I think continuous updating the target KB for linking (and associated embeddings) would be awesome, and we have definitely our plans to do the research necessary to realize this.

We're not specifically looking at BLINK but have started to look deeper into replacing the candidate selection step already, I expect some progress here rather soon. It will be interesting to also consider switching out embeddings for the different modules of REL - I have not really given this deep thoughts yet, but I do think for entity linking to Wikipedia it would degrade effectiveness if we were to move away from `Wikipedia2Vec` embeddings.
