### ISSUE TITLE
AttributeError when using ngram NER

### ISSUE THREAD

**Issue by flackbash** [informagi/REL#138]
Hi again,

I'm trying to integrate REL into our ELEVANT entity linking evaluation tool and most parts are working like a charm now (thank you for your work by the way and also the exhaustive documentation!).
However, when I tried using the ngram NER version with:

```
...
self.ner_tagger = Cmns(base_url, wiki_version, n=5)
mentions_dataset, n_mentions = self.md_model.find_mentions(input_text, self.ner_tagger)
```

I got the error:
```
...
    mentions_dataset, n_mentions = self.md_model.find_mentions(input_text, self.ner_tagger)
  File ".../REL/mention_detection.py", line 149, in find_mentions
    entity.start_position,
AttributeError: 'Span' object has no attribute 'start_position'
```

My uneducated guess is that this happened while fixing #103 with e762cd28a35225113bea04eb31af164b3682b2f3 and now the named tuple `Span` from https://github.com/informagi/REL/blob/main/src/REL/ner/base.py does not match line 149 in find_mentions anymore.

**Comment by KDercksen** [comment]
Hi @flackbash,

I think your guess is correct :) those variable names changed in Flair, we neglected to change them in that file as well. Good find, we will fix it!

**Comment by flackbash** [comment]
Great, thank you :)
