### ISSUE TITLE
Fine-tune REL for queries

### ISSUE THREAD

**Issue by mickvanhulst** [informagi/REL#15]
As previously discussed, REL does not seem to perform well with queries due to e.g. words being mostly lowercase. To handle queries in a more optimal fashion, the following tasks are defined:
- [ ] Re-train ED with a query-based dataset such as GERDAQ. 
- [x] Retrain Flair with lowercase input.
- [x] Truecase the input.

**Comment by arjenpdevries** [comment]
See also https://github.com/informagi/REL/commit/a7fdf34856f3801026b6c6479c36d1b547add8b5
(should have used a branch followed by a merge, apologies!)

**Comment by mickvanhulst** [comment]
Closing as we're using a different process for feature development.
