### ISSUE TITLE
'bert_conv-td' model

### ISSUE THREAD

**Issue by Hcnaeg** [informagi/REL#158]
where to download the 'bert_conv-td' model in this [line](https://github.com/informagi/REL/blob/a61bfc02d7aa713b470f0ed3f83af1c6c72eef8c/src/REL/crel/conv_el.py#L19)? 
I didn't see explanation in tutorial or document

**Comment by stefsmeets** [comment]
It's in the documentation: https://rel.readthedocs.io/en/latest/tutorials/conversations/

**Comment by Hcnaeg** [comment]
> It's in the documentation: https://rel.readthedocs.io/en/latest/tutorials/conversations/

Thank you! I've successfully deployed the server on my machine, however, I found the `ED confidence` returned is always 0.0, is there any solution?

**Comment by stefsmeets** [comment]
@hideaki-j do you have any idea?

**Comment by hideaki-j** [comment]
The personal entity linking module does not use confidence scores. However, if you want to obtain confidence scores, you can follow the instructions:

https://rel.readthedocs.io/en/latest/tutorials/deploy_REL_new_wiki/


> _Now that we have obtained our model, we want to express how confident we are in our prediction. **By default this is not integrated in our model, but we implemented an additional step**, where we use Logistic Regression to obtain confidence scores._

Also, see the corresponding code block which assigns confidence scores:
https://github.com/informagi/REL/blob/0018b575f8106c0986c9bc510a8bc0f0a026c1c5/src/REL/entity_disambiguation.py#L61
