### ISSUE TITLE
Integrate n-gram for mention detection

### ISSUE THREAD

**Issue by mickvanhulst** [informagi/REL#17]
As the title states, integrate n-gram detection for mention detection. This is beneficial for high Recall cases.

TODO:
- [x] Base class implementation
- [x] Alter tutorials, where n-gram may be used as an alternative to Flair.

Details:
1. Implementation is a class similar to Flair.
2. It can be reused by users for a custom MD module.

**Additionally**
Users may use n-gram class as an example for creating their own MD module. Reduces complexity due to prediction on a per sentence basis. Before this update, the user would have to iterate over his/her sentences, give us their results, which would mean iterating twice per sentence. Using this method, the number of iterations per sentence is reduced to one. The function 'find_spans()' will solely be used for ED.

**Comment by arjenpdevries** [comment]
+100

**Comment by mickvanhulst** [comment]
Done
