### ISSUE TITLE
Extend model (NER, ED) loading functionality for custom models using aliases

### ISSUE THREAD

**Issue by KDercksen** [informagi/REL#22]
We would like to implement something similar to what Flair does, i.e.:
```python
model = SequenceTagger.load("alias-for-model")
```

where `alias-for-model` could also point to one of our custom trained models, e.g. CoNLL03 with lowercased entities. Some useful functions would be https://github.com/flairNLP/flair/blob/f5d846ffcaf56d9f90cde484b234685c17a23096/flair/models/sequence_tagger_model.py#L865 and https://github.com/flairNLP/flair/blob/f5d846ffcaf56d9f90cde484b234685c17a23096/flair/file_utils.py#L75, that way we barely have to implement anything :nerd_face:

**Comment by mickvanhulst** [comment]
I think this would be nice, but let's see if we can extend it to work with:
1. ED, which would be easy as it is our own framework.
2. Flair (custom trained models)
3. Sklearn (Logistic Regression, which is used for ED prob).

**Comment by KDercksen** [comment]
So to clarify, you mean creating aliases in all areas where weights can be loaded pretty much? To eliminate downloading e.g. big archives like we have the user do now?

**Comment by mickvanhulst** [comment]
Exactly. In such a case, the users would only have to download our archives once (for the database etc) and not every time we train a new model.

**Comment by KDercksen** [comment]
Okay, then I understood correctly! +1 good idea I think.

**Comment by KDercksen** [comment]
Working on this on `model_aliases` branch.
