### ISSUE TITLE
404

### ISSUE THREAD

**Issue by svakulenk0** [informagi/REL#27]
I keep getting 404 error using the sample request from the README

**Comment by arjenpdevries** [comment]
Just tried my favourite example:

    curl --silent -H "Content-Type: application/json" --request POST --data '{ "text": "Corona virus is spreading in The Netherlands in a similar way as it has in Italy.", "spans": [] }' http://gem.cs.ru.nl/api/ | jq -C

That works fine.

We were working on the web server setup - the example in the README has `rel.cs.ru.nl/api` where mine has `gem.cs.ru.nl/api`, and while the first should be correct now, apparantly there's a glitch.

Meanwhile, you can try with the latter for now - once that starts failing, switch to `rel.cs.ru.nl` which is what it should be. And wait for @mickvanhulst or @KDercksen to update the README.

**Comment by KDercksen** [comment]
Thanks for letting us know! Interestingly, `https://rel.cs.ru.nl/api` seems to work again. Not sure what's going on there... But the example from the README should be working fine now. If this happens again, you can follow Arjen's advice for the time being while we figure out what's up!
