### ISSUE TITLE
what is tagger_ner used for?

### ISSUE THREAD

**Issue by petulla** [informagi/REL#28]
[The part II](https://github.com/informagi/REL/blob/master/tutorials/02_E2E_Entity_Linking.md#pipeline-integration) in the examples define the variable, loading flair fast-ner, but then the utility is never used again.

Is this correct? I'm trying to determine if it's needed at all.. It seems like it should be.

**Comment by KDercksen** [comment]
Different availabe taggers are all instantiated in that tutorial as an example. If you want to use Flair NER, discard the rest. Similarly, if you want to use n-grams, use the Cmns class and discard the rest. Hopefully that clears stuff up!

**Comment by mickvanhulst** [comment]
Thanks for providing the answer @KDercksen, will close the issue.
