### ISSUE TITLE
Reasoning behind Wikipedia2vec and modularity of model

### ISSUE THREAD

**Issue by petulla** [informagi/REL#31]
Hi

I'm just wondering how Wikipedia2vec was arrived at. I know there are other KGE options out there  (I was just presented with a list of TransE, TransR, RESCAL, DistMult, ComplEx, and RotatE).

It seems like swapping out the Wikipedia2vec should be possible but I'm wondering if that's something that's been considered as a possible feature and whether there any known limitations. In the case that a team member wants to use a different model, I'm thinking of how easy it will be to use.

**Comment by arjenpdevries** [comment]
Thanks for the comments, very good questions! We did some experiments with different graph embeddings, there's a brief discussion in Emma Gerritse's (@EmmaGerritse) ECIR paper. We think that the Trans* class will not be competitive. But there are many different developments, and definitely the final word has not yet been said about this topic!

**Comment by petulla** [comment]
Cool. Thanks for the pointers. It seems like the train.sh file could swap out for another library if one seems appropriate in the future. I assume the outputs are something fairly standard like an embedding index.

**Comment by hasibi** [comment]
Hi Sam,

Swapping the embeddings is possible (as you mentioned). In our [paper](https://arxiv.org/abs/2006.01969), we used two different embeddings for our experiments with Wikipedia 2014 and 2019. As discussed in section 4, choosing different embeddings can affect recall in the candidate entity selection step, and accordingly the end performance of the system.  We would be happy to get more updates from you if you try with other embeddings :-)

**Comment by hasibi** [comment]
Hi Sam,

Swapping the embeddings is possible (as mentioned by you and  @arjenpdevries). In our [paper](https://arxiv.org/abs/2006.01969), we used two different embeddings for our experiments with Wikipedia 2014 and 2019. As discussed in section 4, choosing different embeddings can affect recall in the candidate entity selection step, and accordingly the end performance of the system.  We would be happy to get more updates from you if you try with other embeddings :-)

**Comment by KDercksen** [comment]
> Cool. Thanks for the pointers. It seems like the train.sh file could swap out for another library if one seems appropriate in the future. I assume the outputs are something fairly standard like an embedding index.

For completeness sake: as long as you supply an embedding index in the word2vec format, you can use anything you like. Following https://github.com/informagi/REL/blob/master/tutorials/deploy_REL_new_Wiki/04_02_training_your_own_embeddings.md, simply replace the `embedding_file` path with your own embeddings file.

The word2vec format is simply a space-separated line for each word in the index containing:

    word e0 e1 ... eN

where all values after `word` make up the embedding vector.
