### ISSUE TITLE
Possible to get back the Wikipedia2vec vectors from self-serve API?

### ISSUE THREAD

**Issue by petulla** [informagi/REL#34]
Hi

I'm considering standing up an API but was wondering if I could stand it up to get back the trained vectors, particularly if I fine-tune vectors.

So for example with this request:

```python
import requests

IP_ADDRESS = "http://localhost"
PORT = "1235"
text_doc = "If you're going to try, go all the way - Charles Bukowski"

document = {
    "text": text_doc,
    "spans": [],
}

API_result = requests.post("{}:{}".format(IP_ADDRESS, PORT), json=document).json()
```

I'd get back not just the linked entity but the Wiki2vec embedding vector of that linked entity.

Is it much work to set it up this way?

**Comment by mickvanhulst-TomTom** [comment]
Hi Sam,

The trained vectors for Wikipedia2vec are loaded in a sqlite3 database. This database is loaded in the EntityDisambiguation class under the var name 'emb'. So you could address this by using this class, see code example below.
```
from REL.entity_disambiguation import EntityDisambiguation

base_url = ""
wiki_version = ""

config = {
    "mode": "eval",
    "model_path": "{}/{}/generated/model".format(
        base_url, wiki_version
    ),
}

model = EntityDisambiguation(base_url, wiki_version, config)
named_cands = ['ENTITY/Michael_Jackson']
embeddings = model.emb.emb(named_cands, 'embeddings')

```
Alternatively, you can also address the embedding dictionary if this is a postprocessing step, which means that the entity vector will be loaded into memory (note that in this case it is not 'ENTITY/Michael_jackson' but solely 'Michael_Jackson').

```
model.embeddings['entity_embeddings'][entity_name]
```

Any of the options could easily be integrated in the `process_results` function [0] that is called at the end of a server call (see [1] line 131).


[0] https://github.com/informagi/REL/blob/master/REL/utils.py
[1] https://github.com/informagi/REL/blob/master/REL/server.py

**Comment by mickvanhulst** [comment]
Hi Sam,

The trained vectors for Wikipedia2vec are loaded in a sqlite3 database. This database is loaded in the EntityDisambiguation class under the var name 'emb'. So you could address this by using this class, see code example below.
```
from REL.entity_disambiguation import EntityDisambiguation

base_url = ""
wiki_version = ""

config = {
    "mode": "eval",
    "model_path": "{}/{}/generated/model".format(
        base_url, wiki_version
    ),
}

model = EntityDisambiguation(base_url, wiki_version, config)
named_cands = ['ENTITY/Michael_Jackson']
embeddings = model.emb.emb(named_cands, 'embeddings')

```
Alternatively, you can also address the embedding dictionary if this is a postprocessing step, which means that the entity vector will be loaded into memory (note that in this case it is not 'ENTITY/Michael_jackson' but solely 'Michael_Jackson').

```
model.embeddings['entity_embeddings'][entity_name]
```

Any of the options could easily be integrated in the `process_results` function [0] that is called at the end of a server call (see [1] line 131).


[0] https://github.com/informagi/REL/blob/master/REL/utils.py
[1] https://github.com/informagi/REL/blob/master/REL/server.py

**Comment by petulla** [comment]
This is great, thanks. Excited to try it out.
