### ISSUE TITLE
[Bug] Join paths the right way

### ISSUE THREAD

**Issue by ruanchaves** [informagi/REL#38]
Either use `os.path.join` or `pathlib` instead of `+` and `.format` to join paths.

That is, instead of this:

```
"{}/basic_data/wiki_disambiguation_pages.txt".format(self.base_url),
```

You could do this:

```
os.path.join(self.base_url, "/basic_data/wiki_disambiguation_pages.txt")
```

There are several bugs on the master branch ( specially on `REL.wikipedia` and `REL.wikipedia_yago_freq` ) because paths are not being joined in a consistent fashion. I suggest you try to run your own tutorials and then you'll see what I mean. They don't work unless I manually fix the way paths are joined.

**Comment by KDercksen** [comment]
Fully agree! The base_url parameter requires an added slash by the user right now which is unfortunate. I would like to adopt pathlib everywhere, this is already on our planning :) thanks for the feedback!
