### ISSUE TITLE
API for EL seems not working

### ISSUE THREAD

**Issue by lukuang** [informagi/REL#40]
Hi all,

I copy-paste the commands in the tutorial for [API usage](https://github.com/lukuang/REL#querying-our-api), but  I got error when using EL api. ED seems to be fine. The response I got is `HTTP/1.0 400 Bad Request\r\nServer: BaseHTTP/0.6 Python/3.7.3\r\nDate: Tue, 28 Jul 2020 18:35:13 GMT\r\n\r\n`. 

I am wondering if something changed in the server caused this?

**Comment by lukuang** [comment]
OK, I found out why. This is probably a bug. According to [the tutorial of setting up end-to-end EL](https://github.com/informagi/REL/blob/master/tutorials/02_E2E_Entity_Linking.md#setting-up--your-own-api), `spans` needs to be present in the `document`, but it can be an empty list for EL.

**Comment by mickvanhulst-TomTom** [comment]
Hi Lukuang,

That's an error on our side. Our open API is currently using an older version of REL up until we're moving to a new hardware stack :). I will update the README, thanks for notifying us!

**Comment by mickvanhulst** [comment]
Hi Lukuang,

That's an error on our side. Our open API is currently using an older version of REL up until we're moving to a new hardware stack :). I will update the README, thanks for notifying us!

**Comment by lukuang** [comment]
> Hi Lukuang,
> 
> That's an error on our side. Our open API is currently using an older version of REL up until we're moving to a new hardware stack :). I will update the README, thanks for notifying us!

Hi @mickvanhulst, oo problem! Would my PR work? Or you want to fix yourself?

**Comment by mickvanhulst** [comment]
Awesome, thanks a lot for your contribution! Enjoy the rest of your day :).
