### ISSUE TITLE
Mirroring results from public API

### ISSUE THREAD

**Issue by petulla** [informagi/REL#42]
Hi

I setup a mirror of your API internally for use but the results I'm getting back don't look like the public API. I'm wondering if you could share your configuration for the public API.

Ill make a ticket before I leave, but just to give an example for the phrase:

`"If you're going to try, go all the way - Charles Bukowski"`

The public API returns:
`[[41, 16, 'Charles Bukowski', 'Charles_Bukowski', 0.9880370497703552, 'PER', 0.0]]`

The current output I'm seeing is:

`[[24, 14, 'go all the way', 'Key_West', 0.8055737256826012, 28, '#NGRAM#'], [10, 8, 'going to', 'The_League_of_Extraordinary_Gentlemen', 0.7770389829061386, 32, '#NGRAM#'], [16, 7, 'to try,', 'Indian_National_Army_trials', 0.37921062453904336, 2, '#NGRAM#'], [41, 16, 'Charles Bukowski', 'Charles_Bukowski', 0.6841414231561657, 8420, '#NGRAM#'], [0, 2, 'If', 'If_(magazine)', 0.9085130370172767, 2580, '#NGRAM#'], [3, 6, "you're", 'Franklin_D._Roosevelt', 0.26132711208586534, 261, '#NGRAM#']]`

Can you share how to get from the setup in the repo as-is to your results (which are obviously much better!)

**Comment by mickvanhulst-TomTom** [comment]
Hi Sam,

It seems that you are using a different Mention Detection module, namely the ngram module. This is mainly for high recall cases. Let me refer you to our tutorial [0], where we setup two mention detection modules, but given your question I would advice you to use `tagger_ner` and replace it when creating the `server` variable.

Let me know if this works :)!


[0] https://github.com/informagi/REL/blob/master/tutorials/02_E2E_Entity_Linking.md

**Comment by mickvanhulst** [comment]
Hi Sam,

It seems that you are using a different Mention Detection module, namely the ngram module. This is mainly for high recall cases. Let me refer you to our tutorial [0], where we setup two mention detection modules, but given your question I would advice you to use tagger_ner and replace it when creating the server variable.

Let me know if this works :)!

[0] https://github.com/informagi/REL/blob/master/tutorials/02_E2E_Entity_Linking.md

**Comment by petulla** [comment]
I ended up using the fine-tuned lower-cased tagger. It seems very close. Is that the tagger you're using? Have you tested any other NER models?

**Comment by mickvanhulst-TomTom** [comment]
We are actually using the regular tagger from Flair for our APIs. We are currently testing the lower-cased version for other. use-cases. Did it end up working or is there something strange going on :)? Perhaps you can share your code?

**Comment by petulla** [comment]
It did end up working, yes. The lowercase version is very close to the public API; I'll use regular (non-fast) Flair if needed but this seems to be good for now.
