### ISSUE TITLE
About the data of Wikipedia

### ISSUE THREAD

**Issue by xzlyu** [informagi/REL#43]
Thanks for your patient reply in email.
I downloaded the data of wikipedia2014 corpus, I have never seen Wikipedia data of this format, can you show me where to download Wikipedia of this format？To get p(e|m), I need this data, but I can not find Wikipedia data of this format in Wikipedia official website.
Thanks.

**Comment by mickvanhulst-TomTom** [comment]
Thanks for your question!

If you are referring to using our Wikipedia 2014 dump, then you can simply download it from our main Github page. No further preprocessing is required and the sqlite3 database dump already provides you with the required p(e|m) probabilities.

If you want to process your own Wikipedia dump, then please refer to [0]. 

[0] https://github.com/informagi/REL/blob/master/tutorials/deploy_REL_new_Wiki/04_01_Extracting_a_new_Wikipedia_corpus.md

**Comment by xzlyu** [comment]
Thanks.
