### ISSUE TITLE
[Docker] Flair model URL changed + permission issues

### ISSUE THREAD

**Issue by KDercksen** [informagi/REL#46]
Two things are keeping the docker images on Dockerhub from working at the moment;
1. The Flair model repository has changed location (https://github.com/flairNLP/flair/blob/093eba99b7c2fd0007c85e3848188eac5d92e7d3/flair/models/sequence_tagger_model.py#L973)
2. Permissions for files downloaded from REL fileserver are incorrect.

To fix:
1. Rebuilding the images should fix the issue.
2. chown appropriate folders.

Fixes incoming, will close this when done. See also #45

**Comment by ConstantineLignos** [comment]
Is there any estimate on when this will be ready? I have a student doing an evaluation of linking systems this semester and was hoping to include this if the docker images are running in the near future. (And thank you for the work you do to maintain this!)

**Comment by KDercksen** [comment]
Hi Constantine, I'm hoping to fix the prebuilt images anywhere the coming two weeks! It's a bit of a confusing issue.. Alternatively, your student is free to ask for assistance with setting up his/her own environment of course :-)

**Comment by KDercksen** [comment]
Update: the Docker should work again, but you do have to download some data yourself in order to run it successfully. I have updated the instructions in the README as well. I'm closing this issue now, but feel free to ask again if you run into any issues still.
