### ISSUE TITLE
CodeQL fails

### ISSUE THREAD

**Issue by mickvanhulst** [informagi/REL#48]
Added CodeQL and it currently fails when parsing our Java code with the following error:

`  Error: We were unable to automatically build your code. Please replace the call to the autobuild action with your custom build steps.  The process '/opt/hostedtoolcache/CodeQL/0.0.0-20200826/x64/codeql/java/tools/autobuild.sh' failed with exit code 1`

Suggested fix is to ignore Java code in the check.

**Comment by KDercksen** [comment]
+1. It's not immediately obvious to me how to use a custom build and it's not that important for the Java portion of code regardless.

**Comment by mickvanhulst** [comment]
Seems like simply removing 'Java' from the list of languages to verify solved the issue. Alternatively, we could specify folders that we do or do not want to check, but I think our preference is to verify all Python-based files as we ideally will not alter the GERBIL middleware.

Closing.
