### ISSUE TITLE
Problem as I setting up entity linking

### ISSUE THREAD

**Issue by kakatrina** [informagi/REL#57]
As I followed up with tutorial to set up the package, it seems like there is a json file not reading properly. Thanks!
![image](https://user-images.githubusercontent.com/60328340/98468558-06128a00-21a9-11eb-9c1c-6c06406c3aa5.png)
![image](https://user-images.githubusercontent.com/60328340/98468594-28a4a300-21a9-11eb-8786-4ec59d56407f.png)
![image](https://user-images.githubusercontent.com/60328340/98468576-1460a600-21a9-11eb-9b58-2453e8f0736f.png)

**Comment by KDercksen** [comment]
Hi kakatrina,

This seems to be a problem on our side when using `pip install` with a Git repository. I will fix it right now, but in the meantime you can manually download [`models.json`](https://github.com/informagi/REL/blob/master/REL/models/models.json) and save it in directory `~/anaconda3_new/lib/site-packages/REL/models/`. Let me know if that works out!

**Comment by KDercksen** [comment]
Should be fixed, please re-open if you still encounter issues.
