### ISSUE TITLE
multilingual?

### ISSUE THREAD

**Issue by sunc33** [informagi/REL#58]
hello,

Does REL can only be used for English text? Is it available for other language like french if I train it with a french wikipedia corpus?

Best,
Chen SUN

**Comment by mickvanhulst** [comment]
Hi @sunc33,

Currently, we only provide models for English text. Getting REL to work with other languages like French would include:
1. Training Wikipedia2Vec embeddings with a French corpus.
2. Training a new Flair model with a french NER dataset or using their provided models (for french this is 'fr-ner').
3. Training our Entity Disambiguation model on a French ED dataset.

So this is in fact possible and we encourage you to do so! If you do, it would be awesome if you could share the results and models with us such that they can be shared with the public!

Best

Mick

**Comment by mickvanhulst** [comment]
Closing as question seems to be answered :)!
