### ISSUE TITLE
Question about mention-entity prior P(e|m)

### ISSUE THREAD

**Issue by BeerTai** [informagi/REL#60]
Hi, thanks for your project! I have a question about P(e|m). 
In the code, we can get `e` and `m` by extracting text `<a href=entity>mention</a>.` Finally we generate a mention-entity mapping table.
My question is if we recognize a mention from a text, however, the mention may not exist in the mapping table. How do we calculate the prior of the mention？
Can we guarantee that the mention after entity recognition must exist in the mapping table? 
Thanks！

**Comment by mickvanhulst** [comment]
Hi @BeerTai ,

Great question! In short, we can't calculate the prior of the mention. If a mention that was found during our MD step is not present in our p(e|m) index, it will be omitted as we are unable to find any candidate entities for the respective mention.

This also means that there is no guarantee that a mention is present. To increase the odds of finding a mention, we preprocess it slightly if there is no exact match [0].


[0] https://github.com/informagi/REL/blob/master/REL/utils.py#L20
