### ISSUE TITLE
Model for ED confidence score

### ISSUE THREAD

**Issue by vardaan123** [informagi/REL#61]
Hi, where can I find the code to train a model to estimate posterior probabilities of the linked entities (`lr_model.pkl`). Or could you briefly describe how to train such a model?

**Comment by KDercksen** [comment]
Hey vandaan123,

See [this tutorial](https://github.com/informagi/REL/blob/master/tutorials/deploy_REL_new_Wiki/04_04_training_your_own_ED_model.md), the last part describes training a logistic regression model for confidence estimation!
