### ISSUE TITLE
Evaluation on EL

### ISSUE THREAD

**Issue by BeerTai** [informagi/REL#62]
Hi, I am confused about the evaluation of EL.
In ED only, each mention has a correct candidate entity (annotated data), which we can calculate easily F1. 
However, in EL, some mentions extracted by NER may not have a gold result (some mentions are not in the annotation data), or NER model may miss the correct mention existing in the annotation data. 
How can I validate the performance of the EL model (How to calculate F1)? 
Thanks~

**Comment by arjenpdevries** [comment]
You need (to assume) complete annotations. Then, detected mentions missing from the annotation are simply not mentions, and you know all the mentions you missed.
