### ISSUE TITLE
About evaluate on GERBIL

### ISSUE THREAD

**Issue by BeerTai** [informagi/REL#63]
Hi,  I am trying to reproduce the results on the GERBIL platform. 
On my remote server, I start gerbil and receive `Starting Coyote HTTP/1.1 on http-1235.`
I also start the API,and set server_address = ("localhost", 5555).
Finally, I configure an experiment. Where the URI field be filled with:
http://remote_address:1235/gerbil-spotWrapNifWS4Test/myalgorithm.
When I click on the Add Annotator button, I get the error 
```
Warning! There was an error while testing the annotator.
Exception while sending request.
```
what should I do? 
Thanks~

**Comment by KDercksen** [comment]
It looks like port 1235 might not be opened to public access in your remote server.

**Comment by BeerTai** [comment]
Thank you for your reply. I checked the port of the remote server. We test port 1235 with the telnet command. Port 1235 is open.

**Comment by BeerTai** [comment]
When I migrate the code and data from remote to local and then execute it, I still get the same error. At the same time, the terminal did not output any errors or warnings. My api.py as follows:
```
from http.server import HTTPServer

from REL.entity_disambiguation import EntityDisambiguation
from REL.ner import Cmns, load_flair_ner
from REL.server import make_handler

wiki_version = "wiki_2014"
base_url = "/Users/beertai/Desktop/Entity_linking/REL-master/data"

config = {
    "mode": "eval",
    "model_path": "{}/{}/generated/model".format(base_url, wiki_version),  # or alias, see also tutorial 7: custom models
}

model = EntityDisambiguation(base_url, wiki_version, config)

# Using Flair:
tagger_ner = load_flair_ner("ner-fast")

# Alternatively, using n-grams:
tagger_ngram = Cmns(base_url, wiki_version, n=5)

server_address = ("127.0.0.1", 5555)
server = HTTPServer(
    server_address,
    make_handler(
        base_url, wiki_version, model, tagger_ner
    ),
)

try:
    print("Ready for listening.")
    server.serve_forever()
except KeyboardInterrupt:
    exit(0)
```

**Comment by mickvanhulst-TomTom** [comment]
Hi @BeerTai, what about GERBIL middleware [0]? After running that, you should be able to verify if GERBIL is running correctly by going to the respective url [1]. I added a screenshot of what you should see. If this is not what you're seeing, then your port is not correctly setup.

![image](https://user-images.githubusercontent.com/64520930/100576621-c853dd80-32de-11eb-880b-490598aa81ef.png)

[0] https://github.com/informagi/REL/blob/master/tutorials/03_Evaluate_Gerbil.md
[1] http://remote_address:1235/gerbil-spotWrapNifWS4Test/myalgorithm

**Comment by BeerTai** [comment]
Thank you for your reply! I can see the same screenshot as you. Data and code are local. The output of GERBIL middleware as follows:
<img width="1432" alt="Screen Shot 2020-11-30 at 3 14 47 PM" src="https://user-images.githubusercontent.com/29746659/100579352-0b35a580-331f-11eb-9e7b-f9eb1109e8d1.png">
<img width="988" alt="Screen Shot 2020-11-30 at 3 15 34 PM" src="https://user-images.githubusercontent.com/29746659/100579639-7da68580-331f-11eb-815a-e60dc117d628.png">

**Comment by mickvanhulst-TomTom** [comment]
Hi @BeerTai,

You are try to serve GERBIL requests to your local host, this address is only accessible from within your network. You will need to replace this with the a public IP address, which you can find by going to e.g.: https://whatismyipaddress.com/

**Comment by BeerTai** [comment]
Thanks for your reply! I get the same error.
<img width="412" alt="Screen Shot 2020-11-30 at 3 39 49 PM" src="https://user-images.githubusercontent.com/29746659/100581326-864c8b00-3322-11eb-8b35-42fcbfeb5308.png">
<img width="1126" alt="Screen Shot 2020-11-30 at 3 41 58 PM" src="https://user-images.githubusercontent.com/29746659/100581368-9a908800-3322-11eb-804e-13419637365f.png">

**Comment by mickvanhulst-TomTom** [comment]
Hi @BeerTai ,

Have you forwarded your port in your router settings?

**Comment by BeerTai** [comment]
Sorry, I don’t know much about the situation you mentioned, I’m directly connected to the campus network

**Comment by mickvanhulst-TomTom** [comment]
Hi @BeerTai , 

Then you probably have to contact your network administrator and ask him about port forwarding [0]. This is not something we can help you with as it would require network access.

[0] https://en.wikipedia.org/wiki/Port_forwarding

**Comment by BeerTai** [comment]
Thank you very much for your answers!
