### ISSUE TITLE
Requirements for training on Arabic

### ISSUE THREAD

**Issue by lecidhugo** [informagi/REL#65]
Hi,
Is it possible to train the model on Arabic language ?
Is there any specific requirement ?
Thanks in advance,

**Comment by KDercksen** [comment]
Dear lecidhugo,

Essentially it is possible, but you will need to do some work. We use several resources that are language dependent (e.g. word embeddings, entity embeddings, p(entity | mention) index) that you will need to create for yourself. Please look at the tutorials to get some idea of how to get started, and maybe #30 is also helpful (the issue details some efforts on getting REL running for French). If you have any other questions, feel free to create another issue! :)
