### ISSUE TITLE
generic files

### ISSUE THREAD

**Issue by LiuChen19960902** [informagi/REL#67]
Hello, I hope to use this technology in Chinese, but I encountered a problem in the process. I don’t know how to generate crosswikis_p_e_m.txt in the generic directory. Could you please explain to me, Thanks!

**Comment by KDercksen** [comment]
Hi, we did not generate the crosswikis p(e|m) index ourselves. It was a result of [this paper](https://research.google/pubs/pub38098.pdf), maybe that will shed some light!
