### ISSUE TITLE
ED model setup in the docker container 

### ISSUE THREAD

**Issue by nandana** [informagi/REL#68]
I am setting up a local instance of Radboud Entity Linker using a pre-build docker image using the following instructions.

```
docker run 
    -p 5555:5555 
    -v /path/to/generic:/workspace/generic 
    -v /path/to/wiki_2019:/workspace/wiki_2019 
    --rm -it informagi/rel
    python -m REL.server --bind 0.0.0.0 --port 5555 /workspace wiki_2019
```

I wonder how can I configure it to use the downloaded ED model `ed-wiki-2019.tar.gz`? Do I have to put it in a specific page or pass it to the server?

**Comment by arjenpdevries** [comment]
You have to edit `/path/to/wiki_2019 ` to point to the location of this download, on the host. The container then finds it at `/workspace/wiki_2019`.

**Comment by KDercksen** [comment]
If you're using the default ED models, the command you posted will use `ed-wiki-2019` as default (the Docker image will download it when you run the command).

If you want to download it yourself and point the Docker container to it, extract `ed-wiki-2019.tar.gz` and mount the volume accordingly. You also need to supply a flag to the server script, e.g. you can use:
```
docker run
    -p 5555:5555
    -v /path/to/generic:/workspace/generic
    -v /path/to/wiki_2019:/workspace/wiki_2019
    -v /path/to/ed-wiki-2019:/workspace/ed-wiki-2019
    --rm -it informagi/rel
    python -m REL.server --bind 0.0.0.0 --port 5555 --ed-model /workspace/ed-wiki-2019/model /workspace wiki_2019
```

And as mentioned above, make sure your host paths are correct :-)
