### ISSUE TITLE
Using Spacy NER

### ISSUE THREAD

**Issue by g-luo** [informagi/REL#69]
Hello! I already have extracted the named entities from my text using Spacy NER and have the original text / NER label (GPE, PERSON, LOC, etc). I was wondering if / how I could use this in the pipeline to speed up inference?

**Comment by KDercksen** [comment]
Hi g-luo, you can definitely do this! Take a look at our README on calling the web API, as well as the code for the web API handler to get a rough idea: https://github.com/informagi/REL/blob/master/REL/server.py#L111

Basically, you put your documents into the ED-only format `{"doc": ["Amsterdam is a big city...", [(0, 9)]}`. Then you can call the `format_spans` function of a `MentionDetection` class to put the text and spans in the right format for the entity disambiguation model. Then finally, put the results into some output format, like we do in the handler using `utils.process_results`.

```
doc = {"doc": ["Amsterdam is a big city...", [(0, 9)]}
md_model = MentionDetection(base_url, wiki_version)
ed_model = EntityDisambiguation(base_url, wiki_version, {"mode": "eval", "model_path": "ed-wiki-2019"})
mentions_dataset, total_ment = md_model.format_spans(doc)
predictions, timing = ed_model.predict(mentions_dataset)
result = process_results(mentions_dataset, predictions, doc, include_offset=False)
```

Hope that clarifies how to do it! If not, let me know.

**Comment by g-luo** [comment]
Thanks!
