### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by KDercksen** [informagi/REL#7]
To do:

- [x] Add `.travis.yaml` OR use Github workflow
- [x] Write some NER tests
- [x] Write some ED tests

Something to discuss: we cannot really expect certain model outputs, as they might change with updates to the code etc. We probably do not want to upload complete collections of necessary files (e.g. wiki folders, embeddings etc) for each CI run. Thus, I think we either have to mock some parts of the pipeline or accept reaaaally long CI runs. Thoughts?

**Comment by mickvanhulst** [comment]
I agree. The minimum that needs to be done is verify if the output formatting is still valid, meaning that it can, for example, still be parsed by the GERBIL middleware (so output array still has given entity, start position and mention length in the first three index positions).

So my advice would be for us to set up some basic rules as to what the structure of the output should be.

**Comment by Chriskamphuis** [comment]
Maybe upload samples? Like 5 embeddings, 5 wiki pages, etc.
Then you can check easily if everything is behaving consistent right.

**Comment by mickvanhulst** [comment]
A friend of mine also mentioned the use of Github actions, feel free to look into the .git folder of Pandas Profiling.

[0] https://github.com/pandas-profiling/pandas-profiling/tree/master/.github

Additionally:
https://nvie.com/posts/a-successful-git-branching-model/
