### ISSUE TITLE
FutureWarning: The sklearn.linear_model.logistic module is  deprecated in version 0.22 and will be removed in version 0.24.

### ISSUE THREAD

**Issue by Chriskamphuis** [informagi/REL#70]
I get the following warning when using REL: 

FutureWarning: The sklearn.linear_model.logistic module is  deprecated in version 0.22 and will be removed in version 0.24.
The corresponding classes / functions should instead be imported from sklearn.linear_model. Anything that cannot be imported from sklearn.linear_model is now part of the private API.
warnings.warn(message, FutureWarning)

This was after downgrading `scikit-learn`, because it does not work anymore in the newest version of `scikit-learn`.

**Comment by KDercksen** [comment]
To do: retrain LR model with up to date scikit-learn version
