### ISSUE TITLE
`lr_model.pkl` for ED2019

### ISSUE THREAD

**Issue by samarthbhargav** [informagi/REL#71]
I noticed that the `lr_model.pkl` file is missing in the ED2019 model archive. Is it possible to provide this model as well, since there are a quite a few false positives detected otherwise, with no way to filter out low confidence entities.  

For instance, (from the documentation):`Obama will visit Germany. And have a meeting with Merkel tomorrow` gives me the following entities with the 2019 model:

```
[(0, 5, 'Obama', 'Barack_Obama', 0.0, 13399, '#NGRAM#'),
  (6, 4, 'will', 'Will_and_testament', 0.0, 9281, '#NGRAM#'),
  (11, 5, 'visit', 'State_visit', 0.0, 2423, '#NGRAM#'),
  (17, 8, 'Germany.', 'Germany', 0.0, 612, '#NGRAM#'),
  (9, 9, 'a meeting', 'Trump_Tower_meeting', 0.0, 6, '#NGRAM#'),
  (0, 3, 'And', 'Ehud_Olmert', 0.0, 1053, '#NGRAM#'),
  (4, 4, 'have', 'Captain_America_(1990_film)', 0.0, 1988, '#NGRAM#'),
  (19, 4, 'with', 'Two-round_system', 0.0, 1498, '#NGRAM#'),
  (24, 6, 'Merkel', 'Angela_Merkel', 0.0, 1499, '#NGRAM#'),
  (31, 9, 'tomorrow.', 'April_20', 0.0, 25, '#NGRAM#')]
```

**Comment by KDercksen** [comment]
We can do that! In the meantime, I'd advise to use the Flair NER tagger instead of the n-gram approach. The n-gram approach is good for very high recall but as you already found, the precision will suffer quite a lot.

**Comment by samarthbhargav** [comment]
Great, thanks @KDercksen. Is the file going to be released soon? 
Yes, I will switch to the Flair NER tagger as well, thanks!

**Comment by KDercksen** [comment]
I just updated the archives, so the confidence model is now available for 2014 as well as 2019.
