### ISSUE TITLE
Trying to set up with a local endpoint

### ISSUE THREAD

**Issue by Gayathrivenkat4** [informagi/REL#72]
Hello, I downloaded the files and I am trying to run the run_server.py on a linux environment to setup a local endpoint. I get this error :
2021-03-31 14:48:58.259298: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
I0331 14:49:00.938567 139779044779328 textcleaner.py:37] 'pattern' package not found; tag filters are not available for English
Traceback (most recent call last):
  File "run_server.py", line 18, in <module>
    model = EntityDisambiguation(base_url, wiki_version, config)
  File "/home/gv1020/.local/lib/python3.6/site-packages/REL/entity_disambiguation.py", line 49, in __init__
    self.g_emb = GenericLookup("common_drawl", os.path.join(base_url, "generic"))
  File "/home/gv1020/.local/lib/python3.6/site-packages/REL/db/generic.py", line 36, in __init__
    self.db = self.initialize_db(path_db, table_name, columns)
  File "/home/gv1020/.local/lib/python3.6/site-packages/REL/db/base.py", line 41, in initialize_db
    db = sqlite3.connect(fname, isolation_level=None)
sqlite3.OperationalError: unable to open database file

I have installed pattern package as well. Is this something you can help me with? Thanks!

**Comment by KDercksen** [comment]
Did you change the paths in `run_server.py` to the appropriate places for your environment?

**Comment by Gayathrivenkat4** [comment]
Yes I did.. 

base_url = "/home/gv1020/wiki_2019/"
wiki_version = "wiki_2019"

# 1. Init model, where user can set his/her own config that will overwrite the default config.
# If mode is equal to 'eval', then the model_path should point to an existing model.
config = {
    "mode": "eval",
    "model_path": "{}/{}/generated/model".format(base_url, wiki_version),
}

**Comment by KDercksen** [comment]
`wiki_2019` should not be in the base URI. The directory structure should look like this:
```
/home/gv1020
├── generic
└── wiki_2019
```
And then set `base_url = "/home/gv1020"; wiki_version = "wiki_2019"`

**Comment by Gayathrivenkat4** [comment]
Thanks, I tried that but still no luck. Let me show the structure I have now 👍 
/home/gv1020
├── generic
└── wiki_2019
└──code_tutorials
        └──run_server.py
         
I also tried changing the access rights to the **db** directory as the error message says unable to connect- sqllite, however that did not work either. Am i missing any installation?

**Comment by KDercksen** [comment]
Hmm probably not, it is either a permissions problem with the file `generic/common_drawl.db` or a problem with the paths. If the permissions are correct for the db file, could you try doing some print debugs in `REL/db/generic.py` in the `__init__` function, line 11 for example to see what path is passed?

**Comment by StergiosMorakis** [comment]
Not confident that this is the same case but with "_chmod -R 777 ._" on the downloaded files the following error stack trace got resolved for me:
``
    db = sqlite3.connect(fname, isolation_level=None)
    sqlite3.OperationalError: unable to open database file
``
