### ISSUE TITLE
Case sensitivity issue with embeddings used for ED model 2019

### ISSUE THREAD

**Issue by debraj135** [informagi/REL#73]
The wikipedia2vec embeddings used for pretrained ED model 2019 are only for lower case words unlike those used for ED model 2014. 

However, the training seems to be done without taking that into account as a result all words with at least a single upper case letter default to the None or unknown embedding. Is this a bug?

Wouldn't it be better to go with case-sensitive embeddings instead?

**Comment by debraj135** [comment]
On a related note, could you also please detail how the unknown embedding is computed for the glove embedding. Is it a random vector or an average, or perhaps using some other mechanism?

**Comment by KDercksen** [comment]
As far as I can tell you're correct on the casing issue, which is definitely inconsistent with the 2014 model. We are going to look into how this affects performance and how to proceed, thank you very much for pointing this out!

Regarding the unknown GloVe embedding, it is indeed a random vector. See also here: https://github.com/lephong/mulrel-nel/issues/21

**Comment by debraj135** [comment]
Thank you. 

I will look forward to hearing more about the casing issue.

**Comment by debraj135** [comment]
On a related note, is there a reason why the mention words are left out [here](https://github.com/informagi/REL/blob/f6d20e7388a09ce4300f7606668568fd1c5e5926/REL/entity_disambiguation.py#L909) . 

Because of this it seems possible that the `word_voca` doesn't contain it [here](https://github.com/informagi/REL/blob/f6d20e7388a09ce4300f7606668568fd1c5e5926/REL/entity_disambiguation.py#L998) .

**Comment by KDercksen** [comment]
Afaik, words are only left out if they were already seen previously; this reduces cost in embedding successive queries.

**Comment by debraj135** [comment]
Thank you. I do understand that only those words which are unseen aren't left out from [this line](https://github.com/informagi/REL/blob/f6d20e7388a09ce4300f7606668568fd1c5e5926/REL/entity_disambiguation.py#L910) .

I will clarify my question, suppose the sentence is "John is giving a speech.". 

Here the mention is the first word "John". 

Now because of [this line](https://github.com/informagi/REL/blob/f6d20e7388a09ce4300f7606668568fd1c5e5926/REL/entity_disambiguation.py#L909) which uses the `lctx` and `rctx`, the `word_voca` isn't populated with the word "John"  due to which in [this line](https://github.com/informagi/REL/blob/f6d20e7388a09ce4300f7606668568fd1c5e5926/REL/entity_disambiguation.py#L998), uses the id for the unknown token instead.

**Comment by debraj135** [comment]
Has there been any progress on the casing issue?

**Comment by hellahoffmann** [comment]
Any update on this? Could this be why wiki 2014 seems to be perform better than wiki 2019 model on a variety of the eval tasks? I'm seeing a lot of 'UNKN' examples coming through the candidate retrieval step, which then default to none/default embeddings during disambiguation, obviously. 

Would it be save to just use the lower case version when doing the embedding lookup? We're trying to use REL with the latest version of wikipedia and it would be good to know if we should change case sensitivity during P(e|m) and Wiki2Vec embedding computation.

**Comment by KDercksen** [comment]
Hi,

I think that is a safe bet. We found that simply doing lowercase lookup and otherwise keeping everything identical performs comparably to the original version. Retraining disambiguation model might improve it a bit but retraining embeddings is probably the best bet.

Apologies for the long silence, I have tried to retrain the embeddings in order to properly test this but unfortunately keep running into compute issues... 

For reference, see:
original 2019 setup: http://gerbil.aksw.org/gerbil/experiment?id=202002140000
lowercase for embedding lookups (e.g. lowercasing mention and context window after mention detection step): http://gerbil.aksw.org/gerbil/experiment?id=202104200002 (incomplete but shows the gist...)

I'll put a full evaluation here once I finally get everything to work.

**Comment by mickvanhulst** [comment]
Re-opening as wrongfully closed.

**Comment by debraj135** [comment]
Is this supposed to be open?

**Comment by debraj135** [comment]
Hi, I was wondering if this issue was eventually resolved?
