### ISSUE TITLE
High Wall Time?

### ISSUE THREAD

**Issue by spaidataiga** [informagi/REL#81]
Hi, I've followed the tutorial to implement the end-to-end Entity Linking into my processing pipeline for a relatively large number of documents, but it seems to be taking significantly longer than I would expect. While the processing time follows what was reported in the paper (~50 seconds for 100 documents), I've gotten quite a high wall time (25x that of the actual processing time), and I'm not sure why. It seems that most of the wall time is in the Mention Detection stage, and, looking at the code, I can't pinpoint any input/output stage that would cause the wait time.

Could this be an issue in my set-up, or is there something potentially in the code? I've looked through closed issues and have set reset_embeddings=True to see if that would help, following Issue [#52 ](https://github.com/informagi/REL/issues/52) but it made no discernable difference on the run time. Thanks!

**Comment by mickvanhulst** [comment]
Hi @spaidataiga ,

Are the documents of the same size (i.e. # words and # mentions) as reported in our paper? Besides that, I'd require more context to help you out. Perhaps you can share some outputs, how you integrated the pipeline, what mention detection module you are using, and if you are processing documents in batches or not?

Note that resetting the embeddings would only reduce processing time for the Entity Disambiguation step.

**Comment by arjenpdevries** [comment]
If it is MD, you could compare to just running flair on the docs? The costs should be roughly identical.

**Comment by spaidataiga** [comment]
Hi @mickvanhulst , the documents are smaller than those reported. The subset I'm testing on is an average of 28 words per document and 3-5 entities per (I don't have a precise estimate, as I only keep a subset of the entity's linked for processing, and it may take a few hours to run again). The entity linker is implemented exactly following [the tutorial](https://github.com/informagi/REL/blob/master/tutorials/02_E2E_Entity_Linking.md) with wiki version 2019. It is run on Reddit comments that have first been through a coreference resolution step and processing to remove formatting (otherwise normal text). I have tried processing documents in batches as well as one by one, but I haven't seen any difference in runtime. I don't know what output could be helpful, but here are the times I've logged for each of the three main functions of the tutorial. The wall times for all steps are relatively high, which suggests it could be something with my system, but the disparity is greatest for in Mention Detection.

`DEBUG:root:Total Process time: 6148.81
DEBUG:root:Wall time: 153266.1121110916
DEBUG:root:MD Process: 5471.409999999987
DEBUG:root:MD Wall: 143533.51928019524
DEBUG:root:Predict Process: 558.5699999999919
DEBUG:root:Predict Wall: 7375.071177482605
DEBUG:root:Process_results Process: 0.1800000000000921
DEBUG:root:Process_results Wall: 0.26184844970703125`

@arjenpdevries That's a good idea. I'm testing that out right now.

**Comment by spaidataiga** [comment]
@arjenpdevries Interestingly enough, I've run the same subset on just the flair NER tagger, and I get the following times output to me:

`Wall time: 1942.1157355308533
CPU time: 7691.18`

**Comment by arjenpdevries** [comment]
So the total process time is about the same - surprising!

Nothing different in the way the resources used by Flair are provided between the two systems, e.g., local disk vs. network drive? (I'm just hoping for something easy :-))

**Comment by mickvanhulst-TomTom** [comment]
Hi @spaidataiga ,

Given that you are following the tutorial, can I assume that you are passing `tagger_ner` to the `find_mentions()` function? If not, then by default you will be using the n-gram detection module (i.e. `tagger_ngram` object) and it would be great if we could compare the times you reported (Flair) with the complete subsystem so that we can conclude whether or not the problem also persists in native Flair or if it is just a problem that you experience when using REL.

**Comment by spaidataiga** [comment]
@arjenpdevries As far as I can see/tell, I can't imagine so? I am running both processes on a remote compute cluster.  They may be running on different nodes, but there is no difference in how I submit the process.

@mickvanhulst Actually, following the tutorial, I passed tagger_ngram to the find_mentions function. I hadn't done with tagger_ner (even though I had imported it). So I will rerun with tagger_ner so it is more comparable.

**Comment by spaidataiga** [comment]
So with the flair tagger, it runs significantly faster:

On the CPU run time
`DEBUG:root:Total Process time: 9447.75
DEBUG:root:Wall time: 4170.862748861313
DEBUG:root:NER Process: 9131.009999999993
DEBUG:root:NER Wall: 3410.1680092811584
DEBUG:root:Predict Process: 293.3400000000027
DEBUG:root:Predict Wall: 605.9299638271332
DEBUG:root:Process Process: 0.25000000000295586
DEBUG:root:Process Wall: 0.09807801246643066
DEBUG:root:Mapping Process: 17.560000000001487
DEBUG:root:Mapping Wall: 143.90382885932922`
