### ISSUE TITLE
how do you come up with the dev_f1_change_lr value? 

### ISSUE THREAD

**Issue by beviah** [informagi/REL#87]
If I want to use latest wiki, seems this threshold is based on analysis of results? or not?

**Comment by mickvanhulst** [comment]
Hi Beviah,

The threshold for Wikipedia 2014 is based on the original work done by [Le et al.](https://aclanthology.org/P18-1148/), whereas the threshold for Wikipedia 2019 was indeed based on observing the resulting validation scores. We could have done this in a cleaner manner and that with better fine-tuning the results might increase.

Hope this helps :)!

**Comment by beviah** [comment]
yes it does. Thanks :)
