### ISSUE TITLE
sqlite3.OperationalError

### ISSUE THREAD

**Issue by manandey** [informagi/REL#89]
Hi, I am facing this error while using REL. Can you kindly help me fix this?

```
db = sqlite3.connect(fname, isolation_level=None)
sqlite3.OperationalError: unable to open database file
```

**Comment by KDercksen** [comment]
Hi, this is usually a permissions error. Make sure the owner of the db files is the same user that runs the code, and also make sure that the permissions are at least 644 (#72 used 777).

**Comment by manandey** [comment]
Thanks!

**Comment by yzc111** [comment]
Hello, I used sudo to run the docker file and has the same problem...how can i fix it?
