### ISSUE TITLE
OperationalError: unable to open database file

### ISSUE THREAD

**Issue by Vasistareddy** [informagi/REL#93]
c:\............\python\python37\lib\site-packages\REL\db\base.py in initialize_db(self, fname, table_name, columns)
        39         """
        40         # open database in autocommit mode by setting isolation_level to None.
---> 41         db = sqlite3.connect(fname, isolation_level=None)
        42         c = db.cursor()
        43 

OperationalError: unable to open database file

How to resolve it?

**Comment by JoaoFerreira7** [comment]
Hey @Vasistareddy, did you fix this issue? If so, how did you do it? 

Thanks

**Comment by Vasistareddy** [comment]
Check this one [#89](https://github.com/informagi/REL/issues/89). Still, it doesn't work in jupyter notebook and when run with python3 it works.
