### ISSUE TITLE
Not able to use the gerbil middleware

### ISSUE THREAD

**Issue by anmol-rola** [informagi/REL#94]
I tried to run the middleware to evaluate REL. Used the following command to start it -
`http://{YOUR_IP_ADD}:1235/gerbil-spotWrapNifWS4Test/myalgorithm` 

But when I try to add the annotator on gerbil, I am getting the following error.

![Screen Shot 2022-03-19 at 5 50 30 PM](https://user-images.githubusercontent.com/86238956/159120861-3cb50bee-1fea-4b2a-b604-f49a85fd50f9.png)

**Comment by KDercksen** [comment]
Hi @anmol-rola,

Could you share a bit more details? E.g., did you go through the steps here: https://github.com/informagi/REL/blob/main/tutorials/03_Evaluate_Gerbil.md

What Java/Maven version are you running, what is the output of the `mvn` command?

**Comment by KDercksen** [comment]
Hm, I cannot reproduce this on Maven 3.6.0 (same Java version). Maybe you could try that version instead?

I also found this: https://github.com/dice-group/gerbil/issues/243 perhaps this is relevant to your issue.

**Comment by yifding** [comment]
I recommand to try out the gerbil provided by https://github.com/WenzhengZhang/EntQA and it can be run locally. But you have to fix the prediction order of REL. Change the prediction here https://github.com/informagi/REL/blob/main/REL/utils.py#L98 to put pred["prediction"] into the third place, and you are good to go. 

I tested the REL on gerbil locally and it works! The evaluation results are attached here.
[rel_gerbil.pdf](https://github.com/informagi/REL/files/8391323/rel_gerbil.pdf)

**Comment by anmol-rola** [comment]
Hi @yifding thanks for the suggestion. I already tried out gerbil from the mentioned repository. I was able to add annotator but the experiment failed saying that the annotator threw too many single errors. I will try it out again after changing the order as you suggested.
