### ISSUE TITLE
Cache candidates

### ISSUE THREAD

**Issue by chriskamphuis** [informagi/REL#99]
### Problem

In the `MentionDetection` class the function `get_candidates` is called often in a double loop: 

1. https://github.com/informagi/REL/blob/main/REL/mention_detection.py#L48
2. https://github.com/informagi/REL/blob/main/REL/mention_detection.py#L156

The output of this function should be cached for that specific document, documents tend to have mentions that occur multiple times. Now for every time a mention occurs this function is called and a database query is made. The output of this query should be cached such that after a mention is lookup up once for a document, it will be stored until the full document is processed. The `get_candidates` functions takes relatively long, so lowering the database calls would speed up the ED step. 

### Solution
Make a dictionary that caches the mentions for that document that have been retrieved so far, or use the @lru_cache / @cache decorator.

**Comment by arjenpdevries** [comment]
Also here, using a proper join makes sense. 

Overall, REL seems to have moved too many DB operations into client code. Should we use DuckDB all along and not just for data exchange between modules?
